package com.projekt.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerCareTicket implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomerCareTicket() {
    }




}