package com.projekt.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class ReturnOfGoodRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String customerEmail;
	private java.lang.String complaint;

	public ReturnOfGoodRequest() {
	}

	public java.lang.String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(java.lang.String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public java.lang.String getComplaint() {
		return this.complaint;
	}

	public void setComplaint(java.lang.String complaint) {
		this.complaint = complaint;
	}

	public ReturnOfGoodRequest(java.lang.String customerEmail,
			java.lang.String complaint) {
		this.customerEmail = customerEmail;
		this.complaint = complaint;
	}

}